import base64
code = "aW1wb3J0IG9wZXJhdG9yCgoKZGVmIGRlal9udW1iZXIoYSk6CiAgICByZXR1cm4gYQoKCmRlZiBkZWpfbnVybmJlcihhKToKICAgIHJldHVybiBpbnQoYSkKCgpkZWYgZG9kYXdhbmllKHksIHgpOgogICAgcmV0dXJuIG9wZXJhdG9yLmFkZChkZWpfbnVtYmVyKHkpLCBkZWpfbnVtYmVyKHgpKQoKCmRlZiBvZGVqbW93YW5pZSh5LCB4KToKICAgIHJldHVybiBvcGVyYXRvci5zdWIoZGVqX251cm5iZXIoeCksIGRlal9udXJuYmVyKHkpKQoKCmRlZiBkemllbGVuaWUoeSwgeCk6CiAgICByZXR1cm4gb3BlcmF0b3IuZGl2KGRlal9udXJuYmVyKHkpLCBkZWpfbnVybmJlcih4KSkKCgpkZWYgbW5vemVuaWUoeSwgeCk6CiAgICByZXR1cm4gb3BlcmF0b3IubXVsKGRlal9udXJuYmVyKHkpLCBkZWpfbnVtYmVyKHgpKQoKCmRlZiBtYWluKCk6CiAgICB3ID0gMAogICAgeCA9IGlucHV0KCJwb2RhaiBwaWVyd3N6YSBsaWN6YmU6ICIpCiAgICB6ID0gaW5wdXQoInBvZGFqIHpuYWsgZHppYWxhbmlhOiAiKQogICAgeSA9IGlucHV0KCJwb2RhaiBkcnVnYSBsaWN6YmU6ICIpCgogICAgaWYgeiA9PSAiKyI6CiAgICAgICAgdyA9IGRvZGF3YW5pZSh4LCB5KQogICAgZWxpZiB6ID09ICItIjoKICAgICAgICB3ID0gb2Rlam1vd2FuaWUoeCwgeSkKICAgIGVsaWYgeiA9PSAiKiI6CiAgICAgICAgdyA9IG1ub3plbmllKHgsIHkpCiAgICBlbGlmIHogPT0gIi8iOgogICAgICAgIHcgPSBkemllbGVuaWUoeSwgeCkKCiAgICBwcmludCh3KQoKCmlmIF9fbmFtZV9fID09ICdfX21haW5fXyc6CiAgICBtYWluKCkK"
#eval(compile(base64.b64decode(code), '<string>', 'exec'))

decodedBytes = base64.b64decode(code)
decodedStr = str(decodedBytes, "utf-8")

print(decodedStr)